### ISSUE TITLE
npm install fails on ubuntu

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [jedp/node-memwatch-demo#2]
```
> memwatch@0.1.2 install /home/oleksiy/node-memwatch-demo/node_modules/memwatch
> make build

#rm -f bcrypt_lib.node
rm -Rf build
node-waf configure
make: node-waf: Command not found
make: *** [configure] Error 127
```

It needs node-waf, but I can't find how to install this one.

**Comment by leoetlino** [comment]
node-waf has been superseded by node-gyp. Install node-gyp and then symlink node-waf to node-gyp. But then, node-gyp will complain about a missing build file...

**Comment by Oleksiy-Yakovenko** [comment]
Thanks for the response. Sorry for not following up for so long.
